services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: exhibits_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exhibits_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
    container_name: backend
    depends_on:
      - postgres
    environment:
      PORT: 3000
      JWT_SECRET: secret
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: exhibits_admin
      DB_PASSWORD: password
      DB_NAME: exhibits_db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
#    command: [ "npm", "run", "start:prod" ]

#  frontend:
#    build:
#      context: ./front-spa
#    container_name: frontend
#    ports:
#      - "4567:4567"
#    volumes:
#      - ./front-spa:/app

  nginx:
    build:
      context: .
    container_name: nginx
    depends_on:
#      - frontend
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data: